---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: joshlong-tanzu-developer-center-blog-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: joshlong-tanzu-developer-center-blog-cronjob
              image: gcr.io/pgtm-jlong/joshlong-tanzu-developer-center-blog-cronjob
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: joshlong-tanzu-developer-center-blog-cronjob-secrets
          restartPolicy: OnFailure