---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tdc-activity-feed-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: tdc-activity-feed-cronjob-container
              image: gcr.io/bootiful/tdc-activity-feed:latest
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: tdc-activity-feed-secrets
          restartPolicy: OnFailure