---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: activity-feed-cronjob
spec:
  schedule: "10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: activity-feed-cronjob-container
              image: gcr.io/bootiful/feed-processor-v2:latest
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: feed-processor-v2-secrets
          restartPolicy: OnFailure